package com.example.reactivespring.hello;

import org.springframework.http.MediaType;
import org.springframework.stereotype.Component;
import org.springframework.web.reactive.function.BodyInserters;
import org.springframework.web.reactive.function.server.ServerRequest;
import org.springframework.web.reactive.function.server.ServerResponse;
import reactor.core.publisher.Mono;

// In the Spring Reactive approach, we use a handler to handle the request and create a response
@Component
public class GreetingHandler {
/*
This simple reactive class always returns a JSON body with a “Hello, Spring!” greeting.
It could return many other things, including a stream of items from a database,
a stream of items that were generated by calculations, and so on.
Note the reactive code: a Mono object that holds a ServerResponse body.
 */
    public Mono<ServerResponse> hello(ServerRequest request) {
        return ServerResponse.ok().contentType(MediaType.APPLICATION_JSON)
                .body(BodyInserters.fromValue(new Greeting("Hello, Spring!")));
    }
}
